## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: pull_request
    type: docker-image
    source:
      repository: jtarchie/pr

  - name: gcs
    type: docker-image
    source:
        repository: frodenas/gcs-resource

resources:
- name: pgbouncer_pr
  type: pull_request
  source:
    access_token: {{git-access-token}}
    branch: master
    repo: greenplum-db/pgbouncer
    uri: https://github.com/greenplum-db/pgbouncer.git

- name: gpdb7-centos7-build
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-centos7-build

- name: gpdb7-centos7-test
  type: docker-image
  source:
    repository: pivotaldata/gpdb7-centos7-test
    tag: latest

- name: gpdb7_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: bin_gpdb7_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: server/published/master/server-rc-(.*)-rhel7_x86_64.tar.gz

jobs:
- name: test_pgbouncer_gpdb7-centos7
  plan:
  - aggregate:
    - get: pgbouncer_pr
      trigger: true
      version: every
    - get: gpdb7-centos7-build
    - get: gpdb7-centos7-test
    - get: gpdb7_src
    - get: bin_gpdb
      resource: bin_gpdb7_centos7
  - put: pgbouncer_pr
    params:
      path: pgbouncer_pr
      status: pending
  - task: build_pgbouncer
    input_mapping:
      pgbouncer_src: pgbouncer_pr
      gpdb_src: gpdb7_src
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      outputs:
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/build.bash
    image: gpdb7-centos7-build
    on_failure: &pr_failure
      put: pgbouncer_pr
      params:
        path: pgbouncer_pr
        status: failure
    timeout: 30m
  - task: psql_test
    input_mapping:
      gpdb_src: gpdb7_src
      pgbouncer_src: pgbouncer_pr
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/psql_test.bash
    image: gpdb7-centos7-test
    on_failure: *pr_failure
    timeout: 30m


- name: set-pr-status
  plan:
  - aggregate:
    - get: pgbouncer_pr
      trigger: true
      passed:
      - test_pgbouncer_gpdb7-centos7
  - put: report_pr_success
    resource: pgbouncer_pr
    params:
      path: pgbouncer_pr
      status: success
