## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: gcs
    type: docker-image
    source:
        repository: frodenas/gcs-resource

resources:
- name: pgbouncer_src
  type: git
  source:
    access_token: {{git-access-token}}
    branch: {{git-branch}}
    repo: greenplum-db/pgbouncer
    uri: https://github.com/greenplum-db/pgbouncer.git

- name: gpdb7-centos7-build
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-centos7-build

- name: gpdb7-centos7-test
  type: docker-image
  source:
    repository: pivotaldata/gpdb7-centos7-test
    tag: latest

- name: gpdb7-ubuntu18.04-build
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-ubuntu18.04-build
    tag: latest

- name: gpdb7-ubuntu18.04-test
  type: registry-image
  source:
    repository: pivotaldata/gpdb7-ubuntu18.04-test
    tag: latest

- name: gpdb7_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: bin_gpdb7_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: server/published/master/server-rc-(.*)-rhel7_x86_64.tar.gz
- name: bin_gpdb7_ubuntu18.04
  type: gcs
  source:
    bucket: {{gpdb6-bin-bucket-name}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: server/published/master/server-rc-(.*)-ubuntu18.04_x86_64.tar.gz

jobs:
- name: test_pgbouncer_gpdb7_centos7
  plan:
  - in_parallel:
      steps:
      - get: pgbouncer_src
      - get: gpdb7-centos7-build
      - get: gpdb7-centos7-test
      - get: gpdb7_src
      - get: bin_gpdb
        resource: bin_gpdb7_centos7
  - task: build_pgbouncer
    input_mapping:
      gpdb_src: gpdb7_src
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      outputs:
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/build.bash
    image: gpdb7-centos7-build
    timeout: 30m
  - task: psql_test
    input_mapping:
      gpdb_src: gpdb7_src
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/psql_test.bash
    image: gpdb7-centos7-test
    timeout: 30m

- name: test_pgbouncer_gpdb7_ubuntu18.04
  plan:
  - in_parallel:
      steps:
      - get: pgbouncer_src
      - get: gpdb7-ubuntu18.04-build
      - get: gpdb7-ubuntu18.04-test
      - get: gpdb7_src
      - get: bin_gpdb
        resource: bin_gpdb7_ubuntu18.04
  - task: build_pgbouncer
    input_mapping:
      gpdb_src: gpdb7_src
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      outputs:
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/build.bash
    image: gpdb7-ubuntu18.04-build
    timeout: 30m
  - task: psql_test
    input_mapping:
      gpdb_src: gpdb7_src
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      - name: bin_pgbouncer
      run:
        path: pgbouncer_src/concourse/scripts/psql_test.bash
    image: gpdb7-ubuntu18.04-test
    timeout: 30m
