## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: pull_request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
- name: pgbouncer_pr
  type: pull_request
  source:
    branch: pgbouncer_1_8_1
    repo: greenplum-db/pgbouncer
    uri: https://github.com/greenplum-db/pgbouncer.git

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: gpdb_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: bin_gpdb_centos6
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos6/bin_gpdb.tar.gz

jobs:
- name: pgbouncer_test
  plan:
  - aggregate:
    - get: pgbouncer_pr
      trigger: true
      version: every
    - get: centos-gpdb-dev-6
    - get: gpdb_src
    - get: bin_gpdb
      resource: bin_gpdb_centos6
  - put: pgbouncer_pr
    params:
      path: pgbouncer_pr
      status: pending
  - task: build_pgbouncer
    input_mapping:
      pgbouncer_src: pgbouncer_pr
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      run:
        path: pgbouncer_src/concourse/build.bash
    image: centos-gpdb-dev-6
    on_failure: *pr_failure
    timeout: 30m
  - task: psql_test
    input_mapping:
      pgbouncer_src: pgbouncer_pr
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      run:
        path: pgbouncer_src/concourse/psql_test.bash
    image: centos-gpdb-dev-6
    on_failure: *pr_failure
    timeout: 30m
  - task: psql_ssl_test
    input_mapping:
      pgbouncer_src: pgbouncer_pr
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      - name: bin_gpdb
      run:
        path: pgbouncer_src/concourse/psql_ssl_test.bash
    image: centos-gpdb-dev-6
    on_failure: *pr_failure
    timeout: 30m

- name: set-pr-status
  plan:
  - aggregate:
    - get: pgbouncer_pr
      trigger: true
      passed:
      - pgbouncer_test
  - put: report_pr_success
    resource: pgbouncer_pr
    params:
      path: pgbouncer_pr
      status: success
