## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: pull_request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
- name: pgbouncer_pr
  type: pull_request
  source:
    access_token: {{gpss-git-access-token}}
    branch: pgbouncer_1_8_1
    repo: greenplum-db/pgbouncer
    uri: https://github.com/greenplum-db/pgbouncer.git

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: gpdb5_src
  type: git
  source:
    branch: 5X_STABLE
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: gpdb_src
  type: git
  source:
    branch: master
    uri: https://github.com/greenplum-db/gpdb.git
    ignore_paths:
    - gpdb-doc/*
    - README*

jobs:
- name: gpdb5_pgbouncer_test
  plan:
  - aggregate:
    - get: pgbouncer_pr
      trigger: true
      version: every
    - get: centos-gpdb-dev-6
    - get: gpdb5_src
  - put: pgbouncer_pr
    params:
      path: pgbouncer_pr
      status: pending
  - task: build_pgbouncer
    input_mapping:
      pgbouncer_src: pgbouncer_pr
      gpdb_src: gpdb5_src
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      outputs:
      - name: pgbouncer_bin
      run:
        path: pgbouncer_src/concourse/build.bash
    image: centos-gpdb-dev-6
    on_failure: &pr_failure
      put: pgbouncer_pr
      params:
        path: pgbouncer_pr
        status: failure
    timeout: 30m
  - task: psql_test
    input_mapping:
      pgbouncer_src: pgbouncer_bin
      gpdb_src: gpdb5_src
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      run:
        path: pgbouncer_src/concourse/psql_test.bash
    image: centos-gpdb-dev-6
    on_failure: *pr_failure
    timeout: 30m

- name: gpdb6_pgbouncer_test
  plan:
  - aggregate:
    - get: pgbouncer_pr
      trigger: true
      version: every
    - get: centos-gpdb-dev-6
    - get: gpdb_src
  - put: pgbouncer_pr
    params:
      path: pgbouncer_pr
      status: pending
  - task: build_pgbouncer
    input_mapping:
      pgbouncer_src: pgbouncer_pr
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      outputs:
      - name: pgbouncer_bin
      run:
        path: pgbouncer_src/concourse/build.bash
    image: centos-gpdb-dev-6
    on_failure: &pr_failure
      put: pgbouncer_pr
      params:
        path: pgbouncer_pr
        status: failure
    timeout: 30m
  - task: psql_test
    input_mapping:
      pgbouncer_src: pgbouncer_bin
    config:
      platform: linux
      inputs:
      - name: pgbouncer_src
      - name: gpdb_src
      run:
        path: pgbouncer_src/concourse/gpdb6_psql_test.bash
    image: centos-gpdb-dev-6
    on_failure: *pr_failure
    timeout: 30m


- name: set-pr-status
  plan:
  - aggregate:
    - get: pgbouncer_pr
      trigger: true
      passed:
      - gpdb5_pgbouncer_test
      - gpdb6_pgbouncer_test
  - put: report_pr_success
    resource: pgbouncer_pr
    params:
      path: pgbouncer_pr
      status: success
